// আপনার পুরোনো গানের তালিকা, নতুন কাঠামোর সাথে সামঞ্জস্যপূর্ণ করে দেওয়া হলো।

const songs = [
   { name: "আমি তোমার মনের ভিতর..", artist: "Unknown Artist", path: "mp3/A/1.mp3", cover: "img/1.jpg", album: "Bangla" },
   { name: "Dard", artist: "Hindi Songs", path: "mp3/A/2.mp3", cover: "img/2.jpg", album: "Hindi" },
   { name: "Favorite", artist: "Exclusive", path: "mp3/A/3.mp3", cover: "img/3.jpg", album: "Exclusive" },
   { name: "Older", artist: "Exclusive", path: "mp3/A/4.mp3", cover: "img/4.jpg", album: "Exclusive" },
   { name: "Kehta Hain Pal Pal", artist: "Unknown Artist", path: "mp3/A/5.mp3", cover: "img/5.jpg", album: "Hindi" },
   { name: "Lambiya Si Judaiyan", artist: "Arijit Singh", path: "mp3/A/6.mp3", cover: "img/6.jpg", album: "Hindi" },
   { name: "Photo", artist: "Karan Sehmbi", path: "mp3/A/7.mp3", cover: "img/7.jpg", album: "Luka chupi" },
   { name: "Maan Mera", artist: "Gajendra Verma", path: "mp3/A/8.mp3", cover: "img/8.jpg", album: "Hindi" },
   { name: "Aja Ve Mahiya", artist: "Imran Khan", path: "mp3/A/9.mp3", cover: "img/9.jpg", album: "Hindi" },
   { name: "Pal Pal Dil Ke Paas", artist: "Arijit Singh", path: "mp3/A/10.mp3", cover: "img/10.jpg", album: "Hindi" },
   { name: "You and Me", artist: "Shub", path: "mp3/B/11.mp3", cover: "img/11.jpg", album: "Hindi" },
   { name: "Dhinak Dhin Tana", artist: "Udit Narayan", path: "mp3/B/12.mp3", cover: "img/12.jpg", album: "Hindi" },
   { name: "Tu Mile, Dil Khile", artist: "Kumar Sanu", path: "mp3/B/13.mp3", cover: "img/13.jpg", album: "Hindi" },
   { name: "Zara Zara Mehekta Hain", artist: "Bombay Jayashri", path: "mp3/B/14.mp3", cover: "img/14.jpg", album: "Hindi" },
   { name: "Bagal Wali", artist: "DJ", path: "mp3/B/15.mp3", cover: "img/15.jpg", album: "DJ" },
   { name: "Tohar Chara E Jawani", artist: "DJ", path: "mp3/B/16.mp3", cover: "img/16.jpg", album: "DJ | Remix" },
   { name: "Jhuk Jhuk Kare", artist: "DJ", path: "mp3/B/17.mp3", cover: "img/17.jpg", album: "DJ | Remix" },
   { name: "Unknown 18", artist: "Unknown", path: "mp3/B/18.mp3", cover: "img/18.jpg", album: "Unknown" },
   { name: "Unknown 19", artist: "Favorite", path: "mp3/B/19.mp3", cover: "img/19.jpg", album: "Favorite" },
   { name: "Kya Kya", artist: "Akshay Kumar | DJ", path: "mp3/B/20.mp3", cover: "img/20.jpg", album: "DJ | Remix" },
   { name: "Kur Kura Ra", artist: "DJ", path: "mp3/C/21.mp3", cover: "img/21.jpg", album: "DJ | Remix" },
   { name: "Lage Ura Dhura", artist: "DJ", path: "mp3/C/22.mp3", cover: "img/22.jpg", album: "DJ | Remix" },
   { name: "Unknown 23", artist: "Unknown", path: "mp3/C/23.mp3", cover: "img/23.jpg", album: "Unknown" },
   { name: "Industry", artist: "DJ", path: "mp3/C/24.mp3", cover: "img/24.jpg", album: "Remix" },
   { name: "Unknown 25", artist: "DJ", path: "mp3/C/25.mp3", cover: "img/25.jpg", album: "Remix | DJ" },
   { name: "Middle Of The Night", artist: "Elley Duhé", path: "mp3/C/26.mp3", cover: "img/26.jpg", album: "Remix" },
   { name: "Moron o Jodi Ase", artist: "DJ", path: "mp3/C/27.mp3", cover: "img/27.jpg", album: "Remix | DJ" },
   { name: "Na Ja Na Ja", artist: "Pav Dharia", path: "mp3/C/28.mp3", cover: "img/28.jpg", album: "Remix" },
   { name: "Pagal Banaibe", artist: "Khesari Lal Yadav", path: "mp3/C/29.mp3", cover: "img/29.jpg", album: "Bhojpuri | DJ" },
   { name: "Palang Sawanke", artist: "Pawan Singh", path: "mp3/C/30.mp3", cover: "img/30.jpg", album: "Bhojpuri" },
   { name: "Mujhse Shaadi Karogi", artist: "Remix", path: "mp3/D/31.mp3", cover: "img/31.jpg", album: "Remix | DJ" },
   { name: "Unknown 32", artist: "Unknown", path: "mp3/D/32.mp3", cover: "img/32.jpg", album: "Unknown" },
   { name: "Unknown 33", artist: "Unknown", path: "mp3/D/33.mp3", cover: "img/33.jpg", album: "Bhojpuri" },
   { name: "Sundale Sundale", artist: "DJ", path: "mp3/D/34.mp3", cover: "img/34.jpg", album: "Bhojpuri | DJ" },
   { name: "চায়ের কাপে তোমার যত রাগ", artist: "Samz Vai", path: "mp3/D/35.mp3", cover: "img/35.jpg", album: "Bangla" },
   { name: "Top Tucker", artist: "Badshah", path: "mp3/D/36.mp3", cover: "img/36.jpg", album: "Hindi" },
   { name: "দাদা আমার যেমন তেমন", artist: "DJ", path: "mp3/D/37.mp3", cover: "img/37.jpg", album: "DJ | Remix" },
   { name: "বরিশালের লঞ্চ", artist: "নার্গিস", path: "mp3/D/38.mp3", cover: "img/38.jpg", album: "DJ" },
   { name: "রাগ করোনা মনের মানুষ", artist: "DJ", path: "mp3/D/39.mp3", cover: "img/39.jpg", album: "DJ | Remix" }
];