// আপনার পুরোনো গানের তালিকা, নতুন কাঠামোর সাথে সামঞ্জস্যপূর্ণ করে দেওয়া হলো।
// দ্রষ্টব্য: এখানে let এর পরিবর্তে const ব্যবহার করা হয়েছে, যা আধুনিক JavaScript এর নিয়ম।

const All_song = [
   { name: "আমি তোমার মনের ভিতর..", singer: "Unknown Artist", path: "mp3/A/1.mp3", img: "img/1.jpg", album: "Bangla" },
   { name: "Dard", singer: "Hindi Songs", path: "mp3/A/2.mp3", img: "img/2.jpg", album: "Hindi" },
   { name: "Favorite", singer: "Exclusive", path: "mp3/A/3.mp3", img: "img/3.jpg", album: "Exclusive" },
   { name: "Older", singer: "Exclusive", path: "mp3/A/4.mp3", img: "img/4.jpg", album: "Exclusive" },
   { name: "Kehta Hain Pal Pal", singer: "Unknown Artist", path: "mp3/A/5.mp3", img: "img/5.jpg", album: "Hindi" },
   { name: "Lambiya Si Judaiyan", singer: "Arijit Singh", path: "mp3/A/6.mp3", img: "img/6.jpg", album: "Hindi" },
   { name: "Photo", singer: "Karan Sehmbi", path: "mp3/A/7.mp3", img: "img/7.jpg", album: "Luka chupi" },
   { name: "Maan Mera", singer: "Gajendra Verma", path: "mp3/A/8.mp3", img: "img/8.jpg", album: "Hindi" },
   { name: "Aja Ve Mahiya", singer: "Imran Khan", path: "mp3/A/9.mp3", img: "img/9.jpg", album: "Hindi" },
   { name: "Pal Pal Dil Ke Paas", singer: "Arijit Singh", path: "mp3/A/10.mp3", img: "img/10.jpg", album: "Hindi" },
   { name: "You and Me", singer: "Shub", path: "mp3/B/11.mp3", img: "img/11.jpg", album: "Hindi" },
   { name: "Dhinak Dhin Tana", singer: "Udit Narayan", path: "mp3/B/12.mp3", img: "img/12.jpg", album: "Hindi" },
   { name: "Tu Mile, Dil Khile", singer: "Kumar Sanu", path: "mp3/B/13.mp3", img: "img/13.jpg", album: "Hindi" },
   { name: "Zara Zara Mehekta Hain", singer: "Bombay Jayashri", path: "mp3/B/14.mp3", img: "img/14.jpg", album: "Hindi" },
   { name: "Bagal Wali", singer: "DJ", path: "mp3/B/15.mp3", img: "img/15.jpg", album: "DJ" },
   { name: "Tohar Chara E Jawani", singer: "DJ", path: "mp3/B/16.mp3", img: "img/16.jpg", album: "DJ | Remix" },
   { name: "Jhuk Jhuk Kare", singer: "DJ", path: "mp3/B/17.mp3", img: "img/17.jpg", album: "DJ | Remix" },
   { name: "Unknown 18", singer: "Unknown", path: "mp3/B/18.mp3", img: "img/18.jpg", album: "Unknown" },
   { name: "Unknown 19", singer: "Favorite", path: "mp3/B/19.mp3", img: "img/19.jpg", album: "Favorite" },
   { name: "Kya Kya", singer: "Akshay Kumar | DJ", path: "mp3/B/20.mp3", img: "img/20.jpg", album: "DJ | Remix" },
   { name: "Kur Kura Ra", singer: "DJ", path: "mp3/C/21.mp3", img: "img/21.jpg", album: "DJ | Remix" },
   { name: "Lage Ura Dhura", singer: "DJ", path: "mp3/C/22.mp3", img: "img/22.jpg", album: "DJ | Remix" },
   { name: "Unknown 23", singer: "Unknown", path: "mp3/C/23.mp3", img: "img/23.jpg", album: "Unknown" },
   { name: "Industry", singer: "DJ", path: "mp3/C/24.mp3", img: "img/24.jpg", album: "Remix" },
   { name: "Unknown 25", singer: "DJ", path: "mp3/C/25.mp3", img: "img/25.jpg", album: "Remix | DJ" },
   { name: "Middle Of The Night", singer: "Elley Duhé", path: "mp3/C/26.mp3", img: "img/26.jpg", album: "Remix" },
   { name: "Moron o Jodi Ase", singer: "DJ", path: "mp3/C/27.mp3", img: "img/27.jpg", album: "Remix | DJ" },
   { name: "Na Ja Na Ja", singer: "Pav Dharia", path: "mp3/C/28.mp3", img: "img/28.jpg", album: "Remix" },
   { name: "Pagal Banaibe", singer: "Khesari Lal Yadav", path: "mp3/C/29.mp3", img: "img/29.jpg", album: "Bhojpuri | DJ" },
   { name: "Palang Sawanke", singer: "Pawan Singh", path: "mp3/C/30.mp3", img: "img/30.jpg", album: "Bhojpuri" },
   { name: "Mujhse Shaadi Karogi", singer: "Remix", path: "mp3/D/31.mp3", img: "img/31.jpg", album: "Remix | DJ" },
   { name: "Unknown 32", singer: "Unknown", path: "mp3/D/32.mp3", img: "img/32.jpg", album: "Unknown" },
   { name: "Unknown 33", singer: "Unknown", path: "mp3/D/33.mp3", img: "img/33.jpg", album: "Bhojpuri" },
   { name: "Sundale Sundale", singer: "DJ", path: "mp3/D/34.mp3", img: "img/34.jpg", album: "Bhojpuri | DJ" },
   { name: "চায়ের কাপে তোমার যত রাগ", singer: "Samz Vai", path: "mp3/D/35.mp3", img: "img/35.jpg", album: "Bangla" },
   { name: "Top Tucker", singer: "Badshah", path: "mp3/D/36.mp3", img: "img/36.jpg", album: "Hindi" },
   { name: "দাদা আমার যেমন তেমন", singer: "DJ", path: "mp3/D/37.mp3", img: "img/37.jpg", album: "DJ | Remix" },
   { name: "বরিশালের লঞ্চ", singer: "নার্গিস", path: "mp3/D/38.mp3", img: "img/38.jpg", album: "DJ" },
   { name: "রাগ করোনা মনের মানুষ", singer: "DJ", path: "mp3/D/39.mp3", img: "img/39.jpg", album: "DJ | Remix" }
];